ACL_TYPES = [
    {'internalName': 'ACL_ARP',
     'friendlyName': 'Ethernet (mac) address matching',
     'configName': 'arp'},
    {'internalName': 'ACL_BROWSER',
        'friendlyName': 'Regular expression pattern matching on the request user-agent header',
        'configName': 'browser'},
    {'internalName': 'ACL_CA_CERT',
        'friendlyName': 'Match against attributes a users issuing ca ssl certificate',
        'configName': 'ca_cert'},
    {'internalName': 'ACL_DST',
        'friendlyName': 'Destination (server) ip addresses',
        'configName': 'dst'},
    {'internalName': 'ACL_DSTDOMAIN',
        'friendlyName': 'Destination (server) domain name',
        'configName': 'dstdomain'},
    {'internalName': 'ACL_DSTDOM_REGEX',
        'friendlyName': 'Destination (server) regular expression pattern matching',
        'configName': 'dstdom_regex'},
    {'internalName': 'ACL_DST_AS',
        'friendlyName': 'Destination (server) autonomous system number',
        'configName': 'dst_as'},
    {'internalName': 'ACL_EXTERNAL',
        'friendlyName': 'Lookup via external acl helper defined by external_acl_type',
        'configName': 'external'},
    {'internalName': 'ACL_EXT_USER',
        'friendlyName': 'Match on user= field returned by external acl helper defined by external_acl_type',
        'configName': 'ext_user'},
    {'internalName': 'ACL_EXT_USER_REGEX',
        'friendlyName': 'Regular expression pattern matching on user= field returned by external acl helper defined by external_acl_type',
        'configName': 'ext_user_regex'},
    {'internalName': 'ACL_HTTP_STATUS',
        'friendlyName': 'Http response status (200 302 404 etc.)',
        'configName': 'http_status'},
    {'internalName': 'ACL_IDENT',
        'friendlyName': "String matching on the user's name",
        'configName': 'ident'},
    {'internalName': 'ACL_IDENT_REGEX',
        'friendlyName': "Regular expression pattern matching on the user's name",
        'configName': 'ident_regex'},
    {'internalName': 'ACL_MAXCONN',
        'friendlyName': 'A limit on the maximum number of connections from a single client ip address',
        'configName': 'maxconn'},
    {'internalName': 'ACL_MAX_USER_IP',
        'friendlyName': 'A limit on the maximum number of ip addresses one user can login from',
        'configName': 'max_user_ip'},
    {'internalName': 'ACL_METHOD',
        'friendlyName': 'Http request method (get, post, etc)',
        'configName': 'method'},
    {'internalName': 'ACL_MYIP',
        'friendlyName': "The local ip address of a client's connection",
        'configName': 'myip'},
    {'internalName': 'ACL_MYPORT',
        'friendlyName': 'Local port number that client connected to',
        'configName': 'myport'},
    {'internalName': 'ACL_MYPORTNAME',
        'friendlyName': 'Name tag assigned to the squid listening port that client connected to',
        'configName': 'myportname'},
    {'internalName': 'ACL_PEERNAME',
        'friendlyName': 'Name tag assigned to the cache_peer where request is expected to be sent.',
        'configName': 'peername'},
    {'internalName': 'ACL_PORT',
        'friendlyName': 'Destination (server) port number',
        'configName': 'port'},
    {'internalName': 'ACL_PROTO',
        'friendlyName': 'Transfer protocol (http, ftp, etc)',
        'configName': 'proto'},
    {'internalName': 'ACL_PROXY_AUTH',
        'friendlyName': 'User authentication via external processes',
        'configName': 'proxy_auth'},
    {'internalName': 'ACL_PROXY_AUTH_REGEX',
        'friendlyName': 'Regular expression pattern matching on user authentication via external processes',
        'configName': 'proxy_auth_regex'},
    {'internalName': 'ACL_REFERER_REGEX',
        'friendlyName': 'Regular expression pattern matching on the request http-referer header',
        'configName': 'referer_regex'},
    {'internalName': 'ACL_REP_HEADER',
        'friendlyName': 'Regular expression pattern matching on a reply header content. this is only usable in the http_reply_access directive, not http_access.',
        'configName': 'rep_header'},
    {'internalName': 'ACL_REP_MIME_TYPE',
        'friendlyName': 'Regular expression pattern matching on the reply (downloaded content) content-type header. this is only usable in the http_reply_access directive, not http_access.',
        'configName': 'rep_mime_type'},
    {'internalName': 'ACL_REQ_HEADER',
        'friendlyName': 'Regular expression pattern matching on a request header content',
        'configName': 'req_header'},
    {'internalName': 'ACL_REQ_MIME_TYPE',
        'friendlyName': 'Regular expression pattern matching on the request content-type header',
        'configName': 'req_mime_type'},
    {'internalName': 'ACL_SNMP_COMMUNITY',
        'friendlyName': 'Snmp community string matching',
        'configName': 'snmp_community'},
    {'internalName': 'ACL_SRC',
        'friendlyName': 'Source (client) ip addresses',
        'configName': 'src'},
    {'internalName': 'ACL_SRCDOMAIN',
        'friendlyName': 'Source (client) domain name',
        'configName': 'srcdomain'},
    {'internalName': 'ACL_SRCDOM_REGEX',
        'friendlyName': 'Source (client) regular expression pattern matching',
        'configName': 'srcdom_regex'},
    {'internalName': 'ACL_SRC_AS',
        'friendlyName': 'Source (client) autonomous system number',
        'configName': 'src_as'},
    {'internalName': 'ACL_TIME',
        'friendlyName': 'Time of day, and day of week',
        'configName': 'time'},
    {'internalName': 'ACL_URLPATH_REGEX',
        'friendlyName': 'Url-path regular expression pattern matching, leaves out the protocol and hostname',
        'configName': 'urlpath_regex'},
    {'internalName': 'ACL_URL_REGEX',
        'friendlyName': 'Url regular expression pattern matching',
        'configName': 'url_regex'},
    {'internalName': 'ACL_USER_CERT',
        'friendlyName': 'Match against attributes in a user ssl certificate',
        'configName': 'user_cert'}
]
